# QGS communication transport:
#   - To use a Unix domain socket (default), keep the port line commented out.
#   - To use vsock instead, uncomment the line below and set the desired port.
#port = 4050

# Worker thread count
number_threads = 4
